# -*- coding: utf-8 -*-
"""makeup-api..ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m9-8SWW1g2zhklaXLtUdNlVdENZSJidp
"""

url = "http://makeup-api.herokuapp.com/api/v1/products.json"
import requests 

response = requests.get(url)

response.json()[0].keys()

import json
for i in range(100):
    print(str(response.json()[i]["brand"])) #931